### ISSUE TITLE
USER STORY: Django Setup

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#10]
As a **Developer**, I want to **set up Django and install the supporting libraries predicted to be needed**, so that **I am ready to start development**

### Tasks
- [x] Task 1 – Install Django
- [x] Task 2 – Install dj_database_url psycopg2
- [x] Task 3 – Install dj3-cloudinary-storage
- [x] Task 4 – Create a requirements.txt file
- [x] Task 5 – Create the Django project – called pantry
- [x] Task 6 – Create the first app – called recipes and add it to the installed apps in the settings.py

### Epic: #1

**Comment by MattBCoding** [comment]
Completed in commit cbf866365b60504fe06cc1f1158a319a83c59494
