### ISSUE TITLE
USER STORY: Create a User Account

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#13]
As a **User**, I would like **to be able to create an account**, so that **I can create and save recipes**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am an unregistered user
	**When** I am on the homepage
	**Then** I can see a button to sign up
        And, **When** I click on the button
        **Then** I am taken to the user registration page    
- Acceptance Criteria 2
	**Given** that I am an unregistered user
	And, I am on the user registration page
	**When** I enter my username, email address and password
	And, I click on the register button
	**Then** The system creates me an account 
	And, signs me in
- Acceptance Criteria 3
	**Given** that I have an account
	And, I am signed into the account
	**When** I have an option to create a recipe
	And, when I click on that option
	**Then** I am taken to a page where I can provide the details of my recipe
- Acceptance Criteria 4
        **Given** that I am a registered user
        **When** I am signed into my account
        **Then** I do not see the register button
        

## Tasks
- [x] Task 1 – Develop ability for users to register for a user account
- [x] Task 2 – Develop a button in the nav bar to direct users to the registration page
- [x] Task 3 – Remove the register button from the nav bar when users are logged in
- [x] Task 4 - Create a User Registration form
- [x] Task 5 - Create a button in the nav bar to create a recipe directing to a create recipe page

### Epic: #2

**Comment by MattBCoding** [comment]
Task 1 completed on commit - eecc85528432daee1a658580427c4bc42969101f
User Story completed on commit - f83b244d7656dc52efe85658ba57ad4366d367bb
