### ISSUE TITLE
USER STORY: Users can view their profile

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#14]
As a **User**, I would like **to be able to see the details in my user profile**, so that **I can see what information other users can see about me**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am logged into my user account
	**When** I can access an option to view my profile
	**Then** my profile details are displayed as they appear to other users
- Acceptance Criteria 2
	**Given** that I have a user profile, 
	**When** I click on my user name on my user card
	**Then** I can bring up my full user profile as it appears to other users

## Tasks
- [x] Task 1 – Develop a link for users to view their own profile when logged in
- [x] Task 2 – Develop a user card that summarises a users details
- [x] Task 3 - When users click on the user card, they are redirected to the full user profile.

## Epic: #2

**Comment by MattBCoding** [comment]
completed on commit 62e31b8064845e628befba51fdaf7429021ddab9
