### ISSUE TITLE
USER STORY: Users can edit their profile

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#15]
As a **User**, I would like **to be able to edit my profile**, so that **I can keep the information upto date**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am logged into my account
	**When** I am viewing my profile
	**Then** I should be able to edit the details
- Acceptance Criteria 2
	**Given** that I am logged into my account
	**When** I click on the edit button on my profile page
	**Then** I should be taken to a page to edit the details
- Acceptance Criteria 3
	**Given** that I am not logged into my account
	**When** I view my profile page, or anyone elses
	**Then** I should not be able to see the edit button
- Acceptance Criteria 4
	**Given** that I am not logged into my account
	**When** I type in the address to edit my profile, or anyone elses
	**Then** I should be redirected to the log in page.

## Tasks
- [x] Task 1 – Develop the ability for users to edit their own profile
- [x] Task 2 – Develop a page where users can edit the information within their profile
- [x] Task 3 – Add a button to a users profile that only displays when they are logged in and viewing their own profile 
- [x] Task 4 – Prevent users accessing the edit profile page directly, when not logged in
- [x] Task 5 – Prevent users accessing the edit profile page of other users directly, whether logged in or not. 

## Epic: #2

**Comment by MattBCoding** [comment]
Completed on commit 7ff40d00bcf8d4d386df913967d62fd4800dd9e6
