### ISSUE TITLE
USER STORY: Users can delete their account

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#16]
As a **user**, I can **delete my account**, so that **I can remove my details and recipes at my request**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a registered user
	**When** I navigate to my account
	**Then** I have an option to delete my account
- Acceptance Criteria 2
	**Given** that I am a registered user viewing my account details
	**When** I click on the option to delete my account
	**Then** I am requested to confirm the request
- Acceptance Criteria 3
	**Given** that I am a registered user viewing my account details
	**When** I click on the option to delete my account
        And, **When** I confirm the request
	**Then** My account and the recipes that I have created are deleted
- Acceptance Criteria 4
	**Given** that I am a registered user
	**When** I delete my account
	**Then** I should receive confirmation of the account deletion

## Tasks
- [x] Task 1 - On the user account page provide the user with a button to delete their account
- [x] Task 2 - Develop a request confirmation process to confirm the deletion request before it happens
- [x] Task 3 - When the deletion request is confirmed - delete the user account and associated recipes
- [x] Task 4 - Develop a confirmation to the user to show them that the user account and recipes were deleted

**Comment by MattBCoding** [comment]
completed on commit - 631a6178c7c8188ea7554308ac1740b83844dcd2
