### ISSUE TITLE
USER STORY: Users can change their password

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#17]
As a **User**, I would like **to be able to change my password**, so that **I can keep my account secure**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a registered User, logged in to my account
	**When** I navigate to the edit profile page
	**Then** I have the option to change my password
- Acceptance Criteria 2
	**Given** that I am logged in to my account
	**When** I change my password
	**Then** I receive an email confirming my password has been changed
- Acceptance Criteria 3
	**Given** that I am logged into my account
	**When** I try to change my password
	**Then** I am prevented from creating a password that does not meet security requirements
- Acceptance Criteria 4
	**Given** that I am logged into my account
	**When** I click the change password link
	**Then** I am taken to the change password form
	** And When** I correctly complete the form
		And, press submit
	**Then** My password is changed to the new value
		And, I receive confirmation on the screen of the change.

## Tasks
- [x] Task 1 – Develop a form for users to change their password
- [x] Task 2 – Include a link to the form on the edit profile page to change password – this link should only be visible if the user is logged in
- [x] Task 3 – Connect the form to the user profile model, so that the new values entered can be captured in the user model
- [x] Task 4 – Develop form validation to ensure that the password entered meets the requirements
- [x] Task 5 – Develop a feedback notification mechanism to provide users with feedback on the successful, or failure of the password change
- [x] Task 6 – Develop an automated email to the user providing additional confirmation that the password was successfully changed.

**Comment by MattBCoding** [comment]
Completed on commit 44d3b678674a4610911991c8f8db85d8c4217736
Task 6 deemed unnecessary
