### ISSUE TITLE
USER STORY: Users can reset their password

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#18]
As a **User**, I would like **to be able to reset my password**, so that **if I forget it I can still access my account**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a forgetful user
	**When** I try to login with an incorrect password
	**Then** An option is available to reset my password
- Acceptance Criteria 2
	**Given** that I click on the link to reset my password
	**When** I enter my email address that I used to sign up,
	**Then** I should receive an email with instructions on how to reset my password
- Acceptance Criteria 3
	**Given** that I have received the email to reset my password
	**When** I follow the instructions
	**Then** my password should be reset, or I should be able to set a new password of my choosing
	**And When** I do not follow the instructions,
	**Then** my password should not be reset

## Tasks
- [x] Task 1 – Develop a link on the login page to take users to a reset password page
- [x] Task 2 – Develop a form for users to enter their email address in order to reset their password
- [x] Task 3 – Develop an email containing a link to reset the user password
- [x] Task 4 – Ensure form for user to enter email address, validates the email address as belonging to current user.
- [x] Task 5 – Develop time constraint on how long user has to be able to click on the link to reset the password before it expires
- [x] Task 6 – Functionality requires email address – develop validation of email address in initial user registration process.

**Comment by MattBCoding** [comment]
Functionality included with allauth extension. Styling completed on the template on commit d0447d37634b8efc7c2ab24d8b57d6343e273e3f
