### ISSUE TITLE
USER STORY: User Account Login / Logout

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#19]
As a **User**, I would like **to be able to login or logout of my account**, so that **I can keep my account secure**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a registered user, who is not logged in
	**When** I navigate to the sign in page
		And, I enter my credentials correctly and press sign in
	**Then** I am signed into my account
- Acceptance Criteria 2
	**Given** that I am a registered user, who is currently logged in
	**When** I click on the sign out link
	**Then** I am signed out of my account
- Acceptance Criteria 3
	**Given** that I am a registered user, who has signed out of my account
	**When** I use the browser navigation buttons such as back button
	**Then** I can not access information which requires me to be signed in

## Tasks
- [x] Task 1 – Develop the ability for users to sign into their account
- [x] Task 2 – Develop a sign in form to capture user sign in details
- [x] Task 3 – Develop form validation to ensure the data is correct
- [x] Task 4 – Develop a method to validate the data entered matches a user account
- [x] Task 5 – Develop a link for users to sign out of their account – should be accessible from all pages – suggest within nav bar, user account section
- [x] Task 6 – Develop a redirect so if a user signs out whilst on a page requiring a user to be logged in, it redirects them appropriately.

**Comment by MattBCoding** [comment]
Completed in commit f83b244d7656dc52efe85658ba57ad4366d367bb
Task 6 unrequired - utilised allauth for logout. user logs out from logout page.
