### ISSUE TITLE
USER STORY: Features restricted to signed in users

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#20]
As a **Site Owner**, I would like **to restrict some features of the site to registered users**, so that **it encourages people to sign up to the site**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that a user is not registered or signed in,
	**When** they view a recipe,
	**Then** they are unable to save a recipe
- Acceptance Criteria 2
	**Given** that a user is not registered or signed in,
	**When** they look at the recipe options 
	**Then** they do not have the ability to create a recipe
- Acceptance Criteria 3
	**Given** that a user is not registered or signed in,
	**When** they look at a recipe
	**Then** they are unable to provide a rating or comment
- Acceptance Criteria 4
	**Given** that a user is not registered or signed in,
	**When** they encounter functionality that requires them to be signed in
	**Then** they are presented with a login or register button.

## Tasks
- [x] Task 1 – Develop methods to restrict user access to save recipe functionality
- [x] Task 2 – Develop restrictions to user access to create recipe functionality
- [x] Task 3 – Develop restrictions to rating and comment functionality for non logged in users
- [x] Task 4 – For users who are not logged in, develop alternative links to functionality so they can log in/register, and are returned to their original place on the site. E.g. if they want to save a recipe, but are not logged in, when they login, they are taken back to the same recipe.

**Comment by MattBCoding** [comment]
Completed over numerous commits during overall development
