### ISSUE TITLE
USER STORY: Social Media Sign In

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#21]
As a **User**, I would like **to be able to create an account using one of my social media profiles**, so that **I don’t have to remember yet another login**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user who wants to register for an account
	**When** the register page opens,
        **Then** I should be able to select my google account to provide all the required details
- Acceptance Criteria 2
	**Given** that I am a user who wants to register for an account
	**When** the register page opens
        **Then** I should be able to select my Facebook account to provide all the required details
- Acceptance Criteria 3
	**Given** that I am a user who wants to register for an account
	**When** the register page opens
        **Then** I should be able to select my apple account to provide all the required details

## Tasks
- [ ] Task 1 – Develop the ability for users to utilize their google account to register for a user account
- [ ] Task 2 – Develop the ability for users to utilize their Facebook account to register for a user account
- [ ] Task 3 – Develop the ability for users to utilize their apple account to register for a user account
