### ISSUE TITLE
USER STORY: Create a Recipe

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#22]
As a **User**, I would like to be able to **share my own recipes**, with family and friends so they can **teach them to their own children and have fun experiences together baking**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a logged in user
	**When** I navigate to the recipe section
	**Then** I have the option to create a recipe
- Acceptance Criteria 2
	**Given** that I have created a recipe as a logged in user
	**When** I save the completed recipe
	**Then** it is available to other users to view

## Tasks
- [x] Task 1 – Develop a form to enable a user to submit the details for a new recipe
- [x] Task 2 – Develop a model for a recipe record
- [x] Task 3 – Connect the form to the recipe model to create a new recipe record
- [x] Task 4 – Develop the ability to create the record once the recipe has been completed 
- [x] Task 5 – Develop validation for the recipe form to ensure correct information is included

**Comment by MattBCoding** [comment]
Completed on commit 051ef47a962e5c728ee84d450cb4fc11d83ade0e
