### ISSUE TITLE
USER STORY: View recipes

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#23]
As a **user**, I can **access the recipes on the site**, so that **I can follow them at home**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user on the site
	**When** I navigate to the recipes page
	**Then** I am presented with a list of the recipes available
- Acceptance Criteria 2
	**Given** that I am a user on the site
	**When** I navigate to the recipes page
        And **When** I click on a recipe
	**Then** I am presented with the full recipe details

## Tasks
- [x] Task 1 - Develop a link all users can access to the recipes page
- [x] Task 2 - The recipes page should list all of the recipes
- [x] Task 3 - Develop recipe cards that display a summary of the recipe they relate to
- [x] Task 4 - Develop a link from the card to the full recipe details page
- [x] Task 5 - Develop a full recipe details page that provides the full details for the recipe

**Comment by MattBCoding** [comment]
Completed on commit caedd5398901d370a57a92f40e675ed13011a72b
