### ISSUE TITLE
USER STORY: Delete a Recipe

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#25]
As a **user**, I can **delete a recipe that I have created**, so that **I can remove it from the site**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a registered user who is logged in, and has created a recipe
	**When** I navigate to the recipe that I would like to delete
	**Then** I have the option to delete the recipe
- Acceptance Criteria 2
	**Given** that I am a registered user who is logged in, has created a recipe and I am viewing the recipe I wish to delete
	**When** I click the delete recipe button
	**Then** I receive a confirmation window to confirm that I really want to delete the recipe
- Acceptance Criteria 3
	**Given** that I am a registered user who is logged in, has created a recipe, navigated to that recipe and clicked on the delete recipe button
	**When** the confirmation window appears and I confirm the deletion
	**Then** the recipe is deleted from the system
- Acceptance Criteria 4
        **Given** that I am a registered user, or a non registered user
        **When** I navigate to a recipe page that I did not create
        **Then** I do not have the option to delete the recipe

## Tasks
- [x] Task 1 - Develop a delete recipe button that appears on the recipe page when the logged in user is the recipe author
- [x] Task 2 - Develop a deletion confirmation window that appears when the user clicks the delete recipe button
- [x] Task 3 - Develop the code that deletes the recipe record when the user confirms the deletion, provided that the user requesting the deletion is the author
- [x] Task 4 - Prevent unregistered or non original author registered users from deleting the recipe record by navigating to the direct html address.

**Comment by MattBCoding** [comment]
Completed on commit f57fa49698013f59f0f6bb7a3bcbca1aaab51f5d
