### ISSUE TITLE
USER STORY: Save other people's recipes to my profile

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#26]
As a **User**, I would like to be able to **save new recipes**, so that **I can refer back to them easily at a later date**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a signed in user
	**When** I find a recipe I would like to keep
	**Then** I can save it to my own profile
- Acceptance Criteria 2
	**Given** that I am not a signed in user
	**When** I find a recipe I would like to save
	**Then** when I click on save, it reminds me to login
	**And When** I login successfully
	**Then** the recipe I originally wanted to save is saved
- Acceptance Criteria 3
	**Given** that I am an unregistered user
	**When** I find a recipe I would like to save
	**Then** when I click on save, it takes me to the login/register page
	**And When** I successfully register an account
	**Then** the recipe I originally wanted to save is saved

## Tasks
- [x] Task 1 – Develop the ability for users to save a recipe to their profile
- [ ] Task 2 – Develop the ability for the save button to redirect unsigned in users to a login/register page – passing the recipe through so that it can be saved to the profile once it is active
- [x] Task 3 – Develop the save process to provide a visual confirmation to the user that the recipe has been saved

**Comment by MattBCoding** [comment]
Task 1 completed with rating functionality providing the user the ability to like a recipe - which saves it to their own profile. commit 9f009a8bfe94effdc4ac20692bf60cbf9b3f11f6

**Comment by MattBCoding** [comment]
Task 3 completed with visual styling changes to like button on commit 5abce1e6bf3b4cdc15a597646f4385861551b853

Task 2 - reassigned to future product development
