### ISSUE TITLE
USER STORY: Create a list of Favorite Recipes

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#27]
As a **User**, I would like to be able to **save my favourite** recipes, so that **I can find them quickly at a later date**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a signed in user
	**When** I want to look at my saved recipes
	**Then** it should be clear where to find them
- Acceptance Criteria 2
	**Given** that I am a signed in user
	**When** I am looking at recipes I have previously saved
	**Then** I should be able to mark my favourites
- Acceptance Criteria 3
	**Given** that I am a signed in user
	**When** I look at a list of all my saved recipes
	**Then** I should be able to see which are my favourites
- Acceptance Criteria 4
	**Given** that I am a signed in user
	**When** I want to look at only my favourite recipes
	**Then** I should be able to filter my saved recipes to show only the favourites

## Tasks
- [x] Task 1 – Develop functionality for users to mark a saved recipe as a favourite
- [x] Task 2 – Develop a visual indicator on save recipe lists to show which are marked as favourites – this indicator should enable users to toggle the favourite setting
- [x] Task 3 – Develop the ability for users to filter their saved recipe list to show only those marked as favourite
- [x] Task 4 – Develop a clear navigation route for a user to access their saved recipes

**Comment by MattBCoding** [comment]
Task 1 + 2 completed on commit - dcbf50eea31e06ea24181151eabeaaa4374880d4
Task 3 + 4 completed on commit - 23c53b0b341c7e4971aef5b8bdf24a3c96a5f45d
