### ISSUE TITLE
USER STORY: Rate a Recipe

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#29]
As a **User**, I can **give a recipe a rating**, so that **I can provide the author feedback and rank recipes that I like**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a logged in User
	**When** I navigate to a recipe detail page
	**Then** I have the ability to provide a rating
- Acceptance Criteria 2
	**Given** that I am a logged in User
	**When** I navigate to a recipe detail page for a recipe I have previously given a rating
	**Then** I can not provide an additional rating
- Acceptance Criteria 3
	**Given** that I am a logged in user
	**When** I navigate to one of the recipes that I created
	**Then** I can not provide a rating
- Acceptance Criteria 4
	**Given** that I am a user that is not logged in
	**When** I navigate to a recipe detail page
	**Then** I do **not** have the ability to provide a rating

## Tasks
- [x] Task 1 - Develop a rating button for users to provide feedback on a recipe that only shows when logged in
- [x] Task 2 - Prevent Users from submitting more than one review per recipe.
- [x] Task 3 - Prevent Users from submitting a review on a recipe they created

**Comment by MattBCoding** [comment]
Combined rating functionality with saving functionality on commit 9f009a8bfe94effdc4ac20692bf60cbf9b3f11f6
