### ISSUE TITLE
USER STORY: Recipe Rating Details

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#31]
As a **User**, I can **see the individual ratings other users have given one of my recipes**, so that **I can better understand which type of recipes are popular**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a logged in user
	**When** I navigate to one of my recipes
	**Then** I can see the rating provided by individual users
- Acceptance Criteria 2
	**Given** that I am a registered user who is not logged in
	**When** I navigate to one of my recipes
	**Then** I can only see the total average rating provided by other registered users
- Acceptance Criteria 3
	**Given** that I am an unregistered user
	**When** I navigate to a recipe card
	**Then** I can only see the total average rating provided by other users

## Tasks
- [ ] Task 1 - Develop a section on the recipe details page for the recipe author to view the rating details
- [ ] Task 2 - Prevent users who did not author the recipe from seeing the rating breakdown
- [ ] Task 3 - Prevent users from seeing the rating breakdown unless they are the author and logged in.
