### ISSUE TITLE
USER STORY: Give a Recipe a Difficulty Rating

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#32]
As a **User**, I would like **to know how difficult a recipe is before I look at it**, so that **I can avoid the difficult ones**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user of the site
	**When** I am browsing through the list of recipes
	**Then** I should be able to identify the difficulty of each recipe without reading all the details
- Acceptance Criteria 2
	**Given** that I am a user of the site
	**When** viewing recipe options 
	**Then** the difficulty indicator should be colour coded so I can easily recognise the difficulty
- Acceptance Criteria 3
        **Given** that I am a logged in user of the site
        **When** I navigate to a recipe detail page
        **Then** I have the ability to provide a difficulty rating
- Acceptance Criteria 4
        **Given** that I am a logged in user
        **When** I navigate to a recipe detail page for a recipe I have previously given a difficulty rating
	**Then** I can not provide an additional difficulty rating
- Acceptance Criteria 5
	**Given** that I am a user that is not logged in
	**When** I navigate to a recipe detail page
	**Then** I do **not** have the ability to provide a difficulty rating
- Acceptance Criteria 6
	**Given** that I am a logged in user
	**When** I navigate to one of the recipes that I created
	**Then** I can not provide an additional difficulty rating

## Tasks
- [ ] Task 1 – Develop a field for difficulty with the recipe model for the recipe author
- [ ] Task 2 – Include within the recipe overview card the difficulty value by the author
- [ ] Task 3 – Style the difficulty by colour to enable easy recognition
- [ ] Task 4 - Develop a difficulty rating button for users to provide feedback on a recipe that will only appear when the user is logged in.
- [ ] Task 5 - Prevent Users from submitting more than one difficulty rating per recipe
- [ ] Task 6 - Prevent Users from submitting a difficulty rating on their own recipe through the other user difficulty rating system
