### ISSUE TITLE
USER STORY: Recipe Searching - general

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#33]
As a **User**, I would like to be able to **find recipes**, so that **I can increase the variety of meals we consume**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user of the website
	**When** I navigate to the homepage
	**Then** I can access a link to all the recipes
- Acceptance Criteria 2
	**Given** that I am a user of the website
	**When** I enter the recipe section of the site
	**Then** I have options to navigate to different recipe sections
- Acceptance Criteria 3
	**Given** that I am a user of the website
	**When** I want to view a specific recipe
	**Then** I can access the full recipe details by clicking on the recipe

## Tasks
- [x] Task 1 – Develop a recipes link within the main navigation bar
- [x] Task 2 – Develop a link to the recipe section on the main homepage
- [ ] Task 3 – Develop a set link that produces filtered recipe results – such as beef, chicken, curries, cocktails
- [x] Task 4 – Develop a summary card of a recipe to display within results
- [x] Task 5 – Develop a link from the summary card to the main recipe record

**Comment by MattBCoding** [comment]
Tasks 1, 2, 4 & 5 completed on commit b746c308b6e1a54520d2caafff35b189e2c91e16

**Comment by MattBCoding** [comment]
Task 3 relegated to future release
