### ISSUE TITLE
USER STORY: Recipe Search - Advanced

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#34]
As a **User**, I would like to **be able to search the recipes**, so that **I can find the ones that match my fancy at that point in time**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user of the website
	**When** I navigate to the site
	**Then** I can access a search function to access related recipes
- Acceptance Criteria 2
	**Given** that I am a user of the website
	**When** I search the recipes
	**Then** the search results show relevant recipes

## Tasks
- [x] Task 1 – Develop a search field on the homepage and recipe page
- [x] Task 2 – Develop search functionality for the search form for recipe details
- [x] Task 3 – Enable the search query to match either recipe name, creator name, or ingredients

**Comment by MattBCoding** [comment]
completed on commit b746c308b6e1a54520d2caafff35b189e2c91e16
