### ISSUE TITLE
USER STORY: Recipe Search Results - Filter

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#35]
As a **User**, I would like to **be able to filter the recipe search results**, so that **I can refine the matches to my query**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user of the website
	**When** I navigate to the site
	**Then** I can access a search function to access related recipes
- Acceptance Criteria 2
	**Given** that I am a user of the website
	**When** I search the recipes
	**Then** the search results show relevant recipes
- Acceptance Criteria 3
        **Given** I am a user of the website who has conducted a recipe search
        **When** The search results display
        **Then**  I should have the ability to sort the results by date added
- Acceptance Criteria 4
        **Given** I am a user of the website who has conducted a recipe search
        **When** The search results display
        **Then**  I should have the ability to filter the results by difficulty
- Acceptance Criteria 5
        **Given** I am a user of the website who has conducted a recipe search
        **When** The search results display
        **Then**  I should have the ability to filter the results by average rating
- Acceptance Criteria 6
        **Given** I am a user of the website who has conducted a recipe search
        **When** The search results display
        **Then**  I should have the ability to filter the results by meal type - breakfast, lunch, dinner, dessert

## Tasks
- [ ] Task 1 – Develop filter options for the search results display
- [ ] Task 2 - Develop a sort option for the search results display
- [ ] Task 3 – Add a sort option to sort the results by the date added
- [ ] Task 4 – Add a filter option to filter the results by difficulty
- [ ] Task 5 - Add a filter option to filter the results by average rating
- [ ] Task 6 - Add a filter option to filter the results by meal type
