### ISSUE TITLE
USER STORY: Recipe Summary Cards

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#36]
As a **User**, I would like **to be able to view multiple recipes at the same time**, so that **I easily decide which one I want to follow**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user
	**When** I search for or navigate to the full list of recipes
	**Then** The recipes are summarised individually
- Acceptance Criteria 2
	**Given** that I am a user and I have chosen which of the displayed recipes I'd like to select
	**When** I click on the recipe
	**Then** I am taken to the full recipe details

## Tasks
- [x] Task 1 – Develop a clear, UX friendly recipe card layout
- [x] Task 2 – Develop a responsive layout for the recipe cards
- [x] Task 3 – Link the recipe summary cards to the full recipe details page

**Comment by MattBCoding** [comment]
Task 1 and 3 completed on commit 1ab658b3809c067400127bf9cfd6308ad944b2c4
Task 2 also done but will need adjusting once like and favourite functionality available

**Comment by MattBCoding** [comment]
Task 2 completed with favourite button styling on commit - dcbf50eea31e06ea24181151eabeaaa4374880d4
