### ISSUE TITLE
USER STORY: Clear Recipe Layout

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#39]
As a **User**, I would like **clear instructions on how to make each recipe**, so that **I am able to follow along as an inexperienced cook**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user
	**When** I click on a recipe to view the details
	**Then** The instructions on how to make the recipe are clearly accessible
- Acceptance Criteria 2
	**Given** that I am a user accessing the recipe details
	**When** I access a recipe instructions
	**Then** They should be easily to identify the order in which they should be followed

## Tasks
- [x] Task 1 – Develop a clear, UX friendly recipe card layout
- [x] Task 2 – Develop a responsive layout for the recipe cards
- [x] Task 3 – Develop a UI interface that clearly shows the order in which the instructional steps should be followed.

**Comment by MattBCoding** [comment]
Completed on commit 1ab658b3809c067400127bf9cfd6308ad944b2c4
