### ISSUE TITLE
USER STORY: Recipe Questions and Comments

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#40]
As a **User**, I would like to **be able to ask questions if there is something I do not understand**, so that **I can follow the recipe better**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a signed in user
	**When** I review a recipe, if there is something I do not understand
	**Then** I can ask a question in the comments section at the bottom
- Acceptance Criteria 2
	**Given** that I am an unsigned or unregistered user
	**When** I review a recipe, if there is something I do not understand
	**Then** I am prompted to register/sign in before I can comment
- Acceptance Criteria 3
	**Given** that I am an unsigned or unregistered user
	**When** I want to comment on a recipe, and click on the register/sign in link
	**And When** I have completed the registration/sign in process successfully
	**Then** I am returned to the same recipe comments section

## Tasks
- [ ] Task 1 – Develop a comments section at the bottom of a recipe details page
- [ ] Task 2 – Develop the ability for logged in users to post a comment to the comments section
- [ ] Task 3 – Link the comment to the correct recipe
- [ ] Task 4 – Develop an overlay over the comments section that prompts users to sign in, or register in order to comment on a recipe.
- [ ] Task 5 – Develop a button that takes unsigned in, unregistered users to the correct page in order to register or sign in.
- [ ] Task 6 – Develop a redirect so that once the sign in or registration process is correct the user is returned to the correct recipe comments section.
