### ISSUE TITLE
USER STORY: Recipe Question/Comment Notifications

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#41]
As a **User**, I would like to **be notified when someone comments on one of my recipes**, so that **I can respond if necessary**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a registered user, who has created a recipe
	**When** another user leaves a comment on my recipe
	**Then** I am informed that someone has commented
- Acceptance Criteria 2
	**Given** that I am a registered user, who has created a recipe
	**When** another user leaves a comment on my recipe
	**Then** I receive an email telling me that someone has commented
- Acceptance Criteria 3
	**Given** that I am a registered user, who has created a recipe
	**When** another user leaves a comment on my recipe
	** And When** I receive an email telling me they have commented
	**Then** I can also see the comment in the email
- Acceptance Criteria 4
	**Given** that I am a registered user, who has created a recipe
	**When** I receive an email telling me that a user has commented on one of my recipes
	**Then** I also receive a link taking me to the relevant page so that I can respond if needed.

## Tasks
- [ ] Task 1 – Develop a message center for each user
- [ ] Task 2 – Develop a notification indicator that display’s when a user receives a new message
- [ ] Task 3 – Develop message functionality so that a message is sent to a user when someone leaves a comment on a user’s recipe
- [ ] Task 4 – Develop an email template that can be utilised to populate an email body when an email is sent to a user informing them of the comment. The template should include a link to the recipe that was commented on, along with the comment details.
- [ ] Task 5 – Develop an email trigger that sends an email to a user when someone comments on their recipe
