### ISSUE TITLE
USER STORY: User Notification Controls

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#42]
As a **User**, I would like to **be able to turn notifications off for when someone comments on one of my recipes**, so that **I can control the number of notifications that I receive**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a registered user,
	**When** I do not want to receive notifications about comments
	**Then** I can turn them off
- Acceptance Criteria 2
	**Given** that I am a registered user,
	**When** I am creating a recipe
	**Then** I can set the notification setting before publishing the recipe.
- Acceptance Criteria 3
	**Given** that I am a registered user,
	**When** I want to adjust my notification settings
	**Then** I can turn off the email or on-site notifications separately.

## Tasks
- [ ] Task 1 – Develop a setting toggle to enable users to turn on or off the email notifications
- [ ] Task 2 – Develop a setting toggle to enable users to turn on or off the on site notifications
- [ ] Task 3 – Develop a settings toggle within the recipe creation page form to enable users to set the default behaviour for each recipe.
- [ ] Task 4 – Develop an overall toggle to control notifications completely, so that users can turn off all notifications if wanted.
