### ISSUE TITLE
USER STORY: Site Moderation

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#44]
As a **Site Owner**, I would like **to be able to remove inappropriate content from my site**, so that **I can maintain a suitable environment for my users**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that Users have the ability to leave comments or create recipes
	**When** a user creates something, or uses language deemed inappropriate
	**Then** an admin user can delete the comment, or recipe as required.
- Acceptance Criteria 2
	**Given** that the site owner has a superuser level of access
	**When** they determine they need additional moderator support
	**Then** they can provide administrator access to other users
- Acceptance Criteria 3
	**Given** that users have the ability to leave comments or create recipes
	**When** a user repeatedly breaks the rules
	**Then** the administrator/superuser can turn off a users ability to leave comments or create a recipe.
- Acceptance Criteria 4
	**Given** that a user has had the comment or create a recipe functionality removed
	**When** they visit those sections of the site that have those features
	**Then** they are informed that they no longer able to access those features

## Tasks
- [ ] Task 1 – Develop the ability for the superuser to delete comments
- [ ] Task 2 – Develop the ability for the superuser to delete recipes
- [ ] Task 3 – Develop the ability for the superuser to assign admin rights to other users
- [ ] Task 4 – Develop the ability for admin users to delete comments and recipes
- [ ] Task 5 – Develop the ability for admin and superusers to turn off comment and recipe creation functionality for a user.
- [ ] Task 6 – Develop a visual indicator for users that they have had the comment and or recipe creation ability turned off
- [ ] Task 7 – Develop an email template informing users that they have had a comment or recipe deleted by the administrators for breaking the rules.
- [ ] Task 8 – Develop an email template informing users that they have had comment or recipe creation functionality turned off.
