### ISSUE TITLE
USER STORY: Capture User Details

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#45]
As a **Site Owner**, I would like **to capture user details**, so that I can **utilize the volume of users for marketing the site to potential paying customers**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that a user is not registered
	**When** they create an account
	**Then** the system should create that user profile
- Acceptance Criteria 2
	**Given** that a user is not signed in
	**When** they navigate to the newsletter signup
        **Then** they have the ability to enter their email address to sign up for the newsletter
- Acceptance Criteria 3
	**Given** that a user is signed into their account
	**When** they navigate to the newsletter signup
        **Then** they have the ability to sign up for the newsletter without having to enter their email address.
- Acceptance Criteria 4
	**Given** that a user is signed into their account
	**When** they navigate to edit their profile
        **Then** they will have the ability to subscribe/unsubscribe to the newsletter via a checkbox.

## Tasks
- [ ] Task 1 – Develop a method for users to register and create an account
- [ ] Task 2 – develop the ability for visitors to sign up to a newsletter by entering their email address
- [ ] Task 3 – develop validation of the email address for the newsletter sign up
- [ ] Task 4 – develop validation of the email address to prevent duplicate entries
- [ ] Task 5 – develop validation of the email address to prevent duplicate newsletters being sent to users who register for the newsletter and then afterwards create a user account
