### ISSUE TITLE
USER STORY: Pre populate recipe database with an API

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#46]
As a **Site Owner**, I would like **to access a number of existing recipes**, so that I can **provide my users with content whilst building up the user base**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that the site is a new site
	**When** users first visit the site there will be no user generated recipes available
	**And** therefore initial recipe information needs to be provided
	**When** an existing Recipe API is connected
	**Then** it can be utilised to provide the initial recipes to populate the site
- Acceptance Criteria 2
	**Given** that the site is a new site
	**When** the API is connected 
	**Then** users should be able to access all normal search criteria
- Acceptance Criteria 3
	**Given** that a user has found a recipe they like
	**When** they want to see the details
	**Then** they should be able to open the recipe the same as they can with user generated recipes

## Tasks
- [ ] Task 1 – Find a recipe api that provides the desired information
- [ ] Task 2 – Connect the recipe api to the site so that it is searchable
- [ ] Task 3 – Develop the ability for users to see the search results and individual recipe cards from the api results in the same way they would for user generated recipes
- [ ] Task 4 – In the search filters, provide users with the ability to search only the api, or only user generated recipes, or both.
