### ISSUE TITLE
USER STORY: Responsive Templates

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#47]
As a **Site Owner**, I would like **my site to be fully responsive**, so that **users accessing the site from different devices have an enjoyable experience**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user accessing the site on my smartphone
	**When** I navigate through the site
	**Then** all pages should be formatted to my device
- Acceptance Criteria 2
	**Given** that I am a user accessing the site on my tablet
	**When** I navigate through the site
	**Then** all pages should be formatted to my device
- Acceptance Criteria 3
	**Given** that I am a user accessing the site on my laptop
	**When** I navigate through the site
	**Then** all pages should be formatted to my device screen
- Acceptance Criteria 4
	**Given** that I am a user accessing the site on my desktop computer
	**When** I navigate the site 
	**Then** all pages should be formatted to suit my screen size

## Tasks
- [x] Task 1 – Develop all page templates to be fully accessible for mobile devices
- [x] Task 2 – Develop all page templates to be fully responsive for tablet devices
- [x] Task 3 – Develop all page templates to be fully responsive for small monitors
- [x] Task 4 – Develop all page templates to be fully responsive for large monitors
- [x] Task 5 – Develop all user click actions to be accessible via touch

**Comment by MattBCoding** [comment]
Completed over multiple commits - final commit 194f50e16b99a27c2e687efbe3f2065ad9741930
