### ISSUE TITLE
USER STORY: Colour Scheme preference options

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry#48]
As a **Site Owner**, I would like **the site to have a dark colour option**, so that **users have the ability to view the site in a colour scheme they prefer**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that users visit the site on different devices
	**When** their device has a preferred-colour-scheme set
	**Then** the site should be presented in that scheme
- Acceptance Criteria 2
	**Given** that users visit the site 
	**When** they manually set the colour scheme choice
	**Then** the site should remember their preference
- Acceptance Criteria 3
	**Given** that users register for the site
	**When** they log in to the site, 
	**Then** the site should change to their personal colour preference without setting a new preference on that device

## Tasks
- [x] Task 1 – Develop the site to include a light and dark colour scheme
- [x] Task 2 – Develop functionality that checks the user device for a system wide preference
- [x] Task 3 – Develop functionality that checks the user device for a previously set preference
- [ ] Task 4 – Develop a user model colour preference that can be accessed when a user logs into the site
- [x] Task 5 – Develop a manual toggle switch that is easily accessible within the main navigation bar to toggle between the light and dark colour schemes.

**Comment by MattBCoding** [comment]
Tasks 1, 2, 3 and 5 completed on commit a95d34c7e19561343d06a940db6354de3636d6a1

**Comment by MattBCoding** [comment]
Task 4 relegated to future release.
